FROM python:3.9
 
COPY ./client.py /app/client.py
COPY ./requirements_client.txt /app/requirements.txt

WORKDIR /app

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt
 
CMD ["python", "client.py"]