FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9
 
COPY ./main.py /app/main.py
 
WORKDIR /app

# install dependencies
RUN pip install --no-cache-dir fastapi
 
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]